package org.soronc.citydata;

import java.util.HashMap;
import java.util.Map;

public enum Crime {
    
    CRIME_CODE_350("350", "THEFT, PERSON"),
    CRIME_CODE_351("351", "PURSE SNATCHING"),
    CRIME_CODE_670("670", "EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)"),
    CRIME_CODE_230("230", "ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT"),
    CRIME_CODE_352("352", "PICKPOCKET"),
    CRIME_CODE_231("231", "ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER"),
    CRIME_CODE_310("310", "BURGLARY"),
    CRIME_CODE_354("354", "THEFT OF IDENTITY"),
    CRIME_CODE_235("235", "CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT"),
    CRIME_CODE_510("510", "VEHICLE - STOLEN"),
    CRIME_CODE_951("951", "DEFRAUDING INNKEEPER/THEFT OF SERVICES, $400 & UNDER"),
    CRIME_CODE_753("753", "DISCHARGE FIREARMS/SHOTS FIRED"),
    CRIME_CODE_236("236", "SPOUSAL (COHAB) ABUSE - AGGRAVATED ASSAULT"),
    CRIME_CODE_434("434", "FALSE IMPRISONMENT"),
    CRIME_CODE_237("237", "CHILD NEGLECT (SEE 300 W.I.C.)"),
    CRIME_CODE_755("755", "BOMB SCARE"),
    CRIME_CODE_956("956", "LETTERS, LEWD"),
    CRIME_CODE_480("480", "BIKE - STOLEN"),
    CRIME_CODE_440("440", "THEFT PLAIN - PETTY ($950 & UNDER)"),
    CRIME_CODE_121("121", "RAPE, FORCIBLE"),
    CRIME_CODE_122("122", "RAPE, ATTEMPTED"),
    CRIME_CODE_320("320", "BURGLARY, ATTEMPTED"),
    CRIME_CODE_441("441", "THEFT PLAIN - ATTEMPT"),
    CRIME_CODE_761("761", "BRANDISH WEAPON"),
    CRIME_CODE_442("442", "SHOPLIFTING - PETTY THEFT ($950 & UNDER)"),
    CRIME_CODE_762("762", "LEWD CONDUCT"),
    CRIME_CODE_487("487", "BOAT - STOLEN"),
    CRIME_CODE_520("520", "VEHICLE - ATTEMPT STOLEN"),
    CRIME_CODE_443("443", "SHOPLIFTING - ATTEMPT"),
    CRIME_CODE_763("763", "STALKING"),
    CRIME_CODE_886("886", "DISTURBING THE PEACE"),
    CRIME_CODE_888("888", "TRESPASSING"),
    CRIME_CODE_647("647", "THROWING OBJECT AT MOVING VEHICLE"),
    CRIME_CODE_648("648", "ARSON"),
    CRIME_CODE_649("649", "DOCUMENT FORGERY / STOLEN FELONY"),
    CRIME_CODE_928("928", "THREATENING PHONE CALLS/LETTERS"),
    CRIME_CODE_250("250", "SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT"),
    CRIME_CODE_251("251", "SHOTS FIRED AT INHABITED DWELLING"),
    CRIME_CODE_330("330", "BURGLARY FROM VEHICLE"),
    CRIME_CODE_331("331", "THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER)"),
    CRIME_CODE_210("210", "ROBBERY"),
    CRIME_CODE_410("410", "BURGLARY FROM VEHICLE, ATTEMPTED"),
    CRIME_CODE_850("850", "INDECENT EXPOSURE"),
    CRIME_CODE_930("930", "CRIMINAL THREATS - NO WEAPON DISPLAYED"),
    CRIME_CODE_810("810", "SEX, UNLAWFUL"),
    CRIME_CODE_932("932", "PEEPING TOM"),
    CRIME_CODE_812("812", "CHILD, CRIME AGAINST"),
    CRIME_CODE_813("813", "CHILD ANNOYING (17YRS & UNDER)"),
    CRIME_CODE_815("815", "SEXUAL PENTRATION WITH A FOREIGN OBJECT"),
    CRIME_CODE_660("660", "COUNTERFEIT"),
    CRIME_CODE_220("220", "ATTEMPTED ROBBERY"),
    CRIME_CODE_341("341", "THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD"),
    CRIME_CODE_661("661", "UNAUTHORIZED COMPUTER ACCESS"),
    CRIME_CODE_343("343", "SHOPLIFTING-GRAND THEFT ($950.01 & OVER)"),
    CRIME_CODE_662("662", "BUNCO, GRAND THEFT"),
    CRIME_CODE_860("860", "BATTERY WITH SEXUAL CONTACT"),
    CRIME_CODE_420("420", "THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)"),
    CRIME_CODE_421("421", "THEFT FROM MOTOR VEHICLE - ATTEMPT"),
    CRIME_CODE_740("740", "VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)"),
    CRIME_CODE_345("345", "DISHONEST EMPLOYEE - GRAND THEFT"),
    CRIME_CODE_664("664", "BUNCO, PETTY THEFT"),
    CRIME_CODE_940("940", "EXTORTION"),
    CRIME_CODE_622("622", "BATTERY ON A FIREFIGHTER"),
    CRIME_CODE_820("820", "ORAL COPULATION"),
    CRIME_CODE_668("668", "EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)"),
    CRIME_CODE_745("745", "VANDALISM - MISDEAMEANOR ($399 OR UNDER)"),
    CRIME_CODE_624("624", "BATTERY - SIMPLE ASSAULT"),
    CRIME_CODE_625("625", "OTHER ASSAULT"),
    CRIME_CODE_900("900", "VIOLATION OF COURT ORDER"),
    CRIME_CODE_901("901", "VIOLATION OF RESTRAINING ORDER"),
    CRIME_CODE_626("626", "SPOUSAL(COHAB) ABUSE - SIMPLE ASSAULT"),
    CRIME_CODE_627("627", "CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT"),
    CRIME_CODE_902("902", "VIOLATION OF TEMPORARY RESTRAINING ORDER"),
    CRIME_CODE_946("946", "OTHER MISCELLANEOUS CRIME"),
    CRIME_CODE_903("903", "CONTEMPT OF COURT"),
    UNKNOWN("N/A", "UNKNOWN");
    
    private static final Map<String, Crime> CODE_TO_CRIME = new HashMap<>();
    static {
        for(Crime crime: values()){
            Crime previousValue = CODE_TO_CRIME.put(crime.getCode(), crime);
            if(previousValue != null){
                throw new Error("Crimes " +  previousValue.name() + " and " + crime.name() + " have the same code " + crime.getCode());
            }
        }
    }

    private final String code;
    private final String description;
    
    private Crime(String code, String description){
        this.code = code;
        this.description = description;
    }

    
    public String getCode() {
    
        return code;
    }

    
    public String getDescription() {
    
        return description;
    }
    
    public static Crime getCrime(String code){
        return CODE_TO_CRIME.getOrDefault(code, UNKNOWN);
    }
    
}
